[package]
name = "rbac"
version = "0.1.0"
authors = ["Sergey Shlykov <s.shlykov@office.ngs.ru>"]

[dependencies]
mysql = "12.0.3"
json = "0.11.12"                 # JSON implementation in Rust
futures = "*"
time = "*"
iron = "*"
bodyparser = "*"
serde = "*"
serde_json = "*"
persistent = "*"
