[package]
name = "rbac"
version = "0.1.0"
authors = ["Sergey Shlykov <s.shlykov@office.ngs.ru>"]

[dependencies]
mysql = "12.0.3"
json = "0.11.12"                 # JSON implementation in Rust
rocket = "0.3.3"                # Web framework for nightly with a focus on ease-of-use, expressibility, and speed.
rocket_codegen = "0.3.3"        # Code generation for the Rocket web framework.
#rocket_contrib = "0.3.3"        # Community contributed libraries for the Rocket web framework.
time = "*"
serde = "1"
serde_json = "1"
serde_derive = "1"
[dependencies.rocket_contrib]
version = "0.3.3"
default-features = false
features = ["json"]