[package]
name = "rbac"
version = "0.1.0"
authors = ["Sergey Shlykov <s.shlykov@office.ngs.ru>"]

[dependencies]
mysql = "12.0.3"
json = "0.11.12"
futures = "*"
time = "*"
toml = "*"
iron = "*"
bodyparser = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
persistent = "*"
router = "*"
sys-info = "*"
tokio-core = "*"
log = "*"
env_logger = "*"
hyper = "*"